#!/bin/bash

# Invoke maze's runtool, passing to it the following paramaters:
#  arg0 : search strategy or strategies (separated by comma, no space!)

#java -cp lib/maze_runtool-1.1.jar sbst.runtool.Main PCS

#java -cp lib/maze_runtool-1.1.jar sbst.runtool.Main SGS

java -cp lib/maze_runtool-1.1.jar sbst.runtool.Main FOS,COS
